import { langVar, translate } from "../enums";

export const list = [
  {
    patientName: "Jhon Doe",
    problem: "Cervical Spinal Fusion",
    date: "Surgery Date: 2018/11/15",
  },
  {
    patientName: "Jhon Doe",
    problem: "Cervical Spinal Fusion",
    date: " Surgery Date: 2018/11/15",
  },
  {
    patientName: "Jhon Doe",
    problem: "Cervical Spinal Fusion",
    date: " Surgery Date: 2018/11/15",
  },
  {
    patientName: "Jhon Doe",
    problem: "Cervical Spinal Fusion",
    date: " Surgery Date: 2018/11/15",
  },
];

export const messages = [
  {
    name: "Mukthahar shaik rajjab raaj",
    date: new Date(),
    message: "Hai Good morning. How are you feeling today? how is your health",
  },
  {
    name: "Shaik",
    date: new Date(),
    message: "Very Good morning",
  },
];

export const EpisodeoffTrack = [
  {
    name: "Jhon Doe",
    problem: "Cervical Spinal Fusion",
    date: "Procedure Date: Feb 18, 2022",
    trackStatus: "Off-Track",
    navigatorName: "Actovius, Ottoma",
  },
  {
    name: "Jhon Doe",
    problem: "Cervical Spinal Fusion",
    date: "Procedure Date :Feb 18, 2022",
    trackStatus: "Off-Track",
    navigatorName: "Actovius, Ottoma",
  },
  {
    name: "Jhon Doe",
    problem: "Cervical Spinal Fusion",
    date: "Procedure Date: Feb 18, 2022",
    trackStatus: "Off-Track",
    navigatorName: "Actovius, Ottoma",
  },
  {
    name: "Mukthahar Shaik",
    problem: "Cervical Spinal Fusion",
    date: "Procedure Date: Feb 18, 2022",
    trackStatus: "Off-Track",
    navigatorName: "Actovius, Ottoma",
  },
];
export const episodeonTrack = [
  {
    name: "mukthahar",
    problem: "Cervical Spinal Fusion",
    date: "Procedure Date: Feb 18, 2022",
    status: "Disacharged",
    trackStatus: "On-Track",
    navigatorName: "Actovius, Ottoma",
  },
  {
    name: "Shaik",
    problem: "Cervical Spinal Fusion",
    date: "Procedure Date: Feb 18, 2022",
    status: "New",
    trackStatus: "On-Track",
    navigatorName: "Actovius, Ottoma",
  },
  {
    name: "Prince",
    problem: "Cervical Spinal Fusion",
    date: "Procedure Date: Feb 18, 2022",
    status: "On-Hold",
    trackStatus: "On-Track",
    navigatorName: "Actovius, Ottoma",
  },
  {
    name: "Shah",
    problem: "Cervical Spinal Fusion",
    date: "Procedure Date: Feb 18, 2022",
    status: "Processing",
    trackStatus: "On-Track",
    navigatorName: "Actovius, Ottoma",
  },
];

export const patientsDetailsList = [
  { title: translate.t(langVar.patientName), value: "John Deo" },
  { title: translate.t(langVar.age), value: "65 years" },
  {
    title: translate.t(langVar.procedure),
    value: "A Cervical Spinal Fusion (10/28/21)",
  },
  { title: translate.t(langVar.laterality), value: "None" },
  { title: translate.t(langVar.days90), value: "1/29/22" },
  { title: translate.t(langVar.status), value: "Off Track" },
];

export const transitionofDays = [
  { label: "Acute Days", value: 7 },
  { label: "IRF Days", value: 0 },
  { label: "SNF Days", value: 4 },
  { label: "HH Visits", value: 0 },
  { label: "OPT Visits", value: 0 },
  { label: "M-OPT Visits", value: 0 },
];

export const episodeAllList = {
  offtrackPatients: [
    {
      PatientFirstName: "Test2000",
      PatientLastName: "LOADTEST_2000",
      PatientDOB: "1945-05-22T00:00:00",
      PatientPhoneCell: "",
      PatientPhoneHome: "",
      PatientPhoneWork: "",
      EpisodeName: "Acute myocardial infarction",
      EpisodeID: 1076,
      IntakeStatus: "New",
      IntakeStatusID: 1,
      IntakeSurgeryDate: "2019-05-10T00:00:00",
      IntakeSurgerySide: "N/A",
      IntakeSurgerySite: "N/A",
      ProviderName: "Hospice1 Test1",
      ProviderTypeCode: "HSP",
      ProviderPhone: "1-888-111-1116",
      TrackStatus: "OnTrack",
      NavigatorName: "1111-2002, DebbieM",
    },
    {
      PatientFirstName: "Test2000",
      PatientLastName: "LOADTEST_2000",
      PatientDOB: "1945-05-22T00:00:00",
      NavigatorName: "1111-2002, DebbieM",
      PatientPhoneCell: "",
      PatientPhoneHome: "",
      PatientPhoneWork: "",
      EpisodeName: "Acute myocardial infarction",
      EpisodeID: 1076,
      IntakeStatus: "New",
      IntakeStatusID: 1,
      IntakeSurgeryDate: "2019-05-10T00:00:00",
      IntakeSurgerySide: "N/A",
      IntakeSurgerySite: "N/A",
      ProviderName: "Hospice1 Test1",
      ProviderTypeCode: "HSP",
      ProviderPhone: "1-888-111-1116",
      TrackStatus: "OnTrack",
    },
  ],
  ontrackPatients: [
    {
      PatientFirstName: "Test2000",
      PatientLastName: "LOADTEST_2000",
      PatientDOB: "1945-05-22T00:00:00",
      PatientPhoneCell: "",
      PatientPhoneHome: "",
      PatientPhoneWork: "",
      EpisodeName: "Acute myocardial infarction",
      NavigatorName: "Kannan-Smoke, Aruna",
      EpisodeID: 1076,
      IntakeStatus: "New",
      IntakeStatusID: 1,
      IntakeSurgeryDate: "2019-05-10T00:00:00",
      IntakeSurgerySide: "N/A",
      IntakeSurgerySite: "N/A",
      CurrentLocationName: "Spaulding Rehab Center",
      ProviderName: "Hospice1 Test1",
      ProviderTypeCode: "HSP",
      ProviderPhone: "1-888-111-1116",
      TrackStatus: "OnTrack",
    },
    {
      PatientFirstName: "Arya",
      PatientLastName: "Lost-eSignature",
      PatientDOB: "1930-03-01T00:00:00",
      PatientPhoneCell: "508-333-1137",
      PatientPhoneHome: null,
      PatientPhoneWork: "508-555-1136",
      NavigatorName: "Kannan-Smoke, Aruna",
      NavigatorPhone: null,
      EpisodeName: "Major joint replacement of the lower extremity",
      EpisodeID: 1095,
      IntakeID: 10776,
      IntakeStatus: "Processing",
      IntakeStatusID: 7,
      IntakeSurgeryDate: "2018-12-17T00:00:00",
      IntakeSurgerySide: "Left",
      IntakeSurgerySite: "Foot",
      SurgeryLocationName: "Spaulding Rehab Center",
      SurgeryLocationID: 8888,
      SurgeryLocationPhone: null,
      CurrentLocationName: "Spaulding Rehab Center",
      CurrentLocationID: 8894,
      CurrentLocationType: "HWN",
      TrackStatus: "ToC Not Created",
    },
  ],
};

export const recentContactList: any[] = [
  // {
  //   recordID: 1,
  //   givenName: "John",
  //   familyName: "Doe",
  //   thumbnailPath:
  //     "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
  //   hasThumbnail: true,
  //   phoneNumbers: "1234567890",
  //   description: "Navigator",
  //   contactType: "Navigator",
  // },
  // {
  //   recordID: 2,
  //   givenName: "John",
  //   familyName: "Smith",
  //   thumbnailPath:
  //     "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
  //   hasThumbnail: true,
  //   phoneNumbers: "1234567890",
  //   description: "Navigator",
  //   contactType: "Navigator",
  // },
  // {
  //   recordID: 3,
  //   givenName: "Brann",
  //   familyName: "Stark",
  //   thumbnailPath:
  //     "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
  //   hasThumbnail: false,
  //   phoneNumbers: "1234567890",
  //   description: "Cervical Spinal Fusion",
  //   contactType: "Patients",
  // },
];
export const initialContactList: any[] = [
  {
    recordID: 1,
    givenName: "John",
    familyName: "Doe",
    phoneNumbers: "1234567890",
    description: "Navigator",
    contactType: "Navigator",
  },
  {
    recordID: 2,
    givenName: "John",
    familyName: "Smith",
    thumbnailPath:
      "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
    hasThumbnail: true,
    phoneNumbers: "1234567890",
    description: "Navigator",
    contactType: "Navigator",
  },
  {
    recordID: 3,
    givenName: "Brann",
    familyName: "Stark",
    thumbnailPath:
      "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
    hasThumbnail: false,
    phoneNumbers: "1234567890",
    description: "Cervical Spinal Fusion",
    contactType: "Patients",
  },
  {
    recordID: 4,
    givenName: "Twilla",
    familyName: "Price",
    thumbnailPath:
      "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
    hasThumbnail: false,
    phoneNumbers: "1234567890",
    description: "Navigator",
    contactType: "Navigator",
  },
  {
    recordID: 5,
    givenName: "Ned",
    familyName: "Stark",
    thumbnailPath:
      "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
    hasThumbnail: true,
    phoneNumbers: "1234567890",
    description: "Spine C4 to L2 Replacement",
    contactType: "Patients",
  },
  {
    recordID: 6,
    givenName: "Monika",
    familyName: "Doe",
    thumbnailPath:
      "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
    hasThumbnail: false,
    phoneNumbers: "1234567890",
    description: "Navigator",
    contactType: "Navigator",
  },
  {
    recordID: 7,
    givenName: "John",
    familyName: "Doe",
    thumbnailPath:
      "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
    hasThumbnail: true,
    phoneNumbers: "1234567890",
    description: "Navigator",
    contactType: "Navigator",
  },
  {
    recordID: 8,
    givenName: "John",
    familyName: "Smith",
    thumbnailPath:
      "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
    hasThumbnail: true,
    phoneNumbers: "1234567890",
    description: "Navigator",
    contactType: "Navigator",
  },
  {
    recordID: 9,
    givenName: "Brann",
    familyName: "Stark",
    thumbnailPath:
      "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
    hasThumbnail: false,
    phoneNumbers: "1234567890",
    description: "Cervical Spinal Fusion",
    contactType: "Patients",
  },
  {
    recordID: 10,
    givenName: "Twilla",
    familyName: "Price",
    thumbnailPath:
      "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
    hasThumbnail: false,
    phoneNumbers: "1234567890",
    description: "Navigator",
    contactType: "Navigator",
  },
  {
    recordID: 11,
    givenName: "Ned",
    familyName: "Stark",
    thumbnailPath:
      "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
    hasThumbnail: true,
    phoneNumbers: "1234567890",
    description: "Spine C4 to L2 Replacement",
    contactType: "Patients",
  },
  {
    recordID: 12,
    givenName: "Monika",
    familyName: "Doe",
    thumbnailPath:
      "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
    hasThumbnail: false,
    phoneNumbers: "1234567890",
    description: "Navigator",
    contactType: "Navigator",
  },
  {
    recordID: 13,
    givenName: "Ned",
    familyName: "Stark",
    thumbnailPath:
      "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
    hasThumbnail: true,
    phoneNumbers: "1234567890",
    description: "Navigator",
    contactType: "Navigator",
  },
  {
    recordID: 14,
    givenName: "Monika",
    familyName: "Doe",
    thumbnailPath:
      "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
    hasThumbnail: false,
    phoneNumbers: "1234567890",
    description: "Navigator",
    contactType: "Navigator",
  },
  {
    recordID: 15,
    givenName: "zzzzzzzzz",
    familyName: "Doe",
    thumbnailPath:
      "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
    hasThumbnail: false,
    phoneNumbers: "1234567890",
    description: "Navigator",
    contactType: "Navigator",
  },
  {
    recordID: 16,
    givenName: "zzzzzzzzz",
    familyName: "Doe",
    thumbnailPath:
      "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
    hasThumbnail: false,
    phoneNumbers: "1234567890",
    description: "Navigator",
    contactType: "Navigator",
  },
  {
    recordID: 17,
    givenName: "zzzzzzzzz",
    familyName: "Doe",
    thumbnailPath:
      "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
    hasThumbnail: false,
    phoneNumbers: "1234567890",
    description: "Navigator",
    contactType: "Navigator",
  },
  {
    recordID: 18,
    givenName: "zzzzzzzzz",
    familyName: "Doe",
    thumbnailPath:
      "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
    hasThumbnail: false,
    phoneNumbers: "1234567890",
    description: "Navigator",
    contactType: "Navigator",
  },
  {
    recordID: 19,
    givenName: "zzzzzzzzz",
    familyName: "Doe",
    thumbnailPath:
      "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
    hasThumbnail: false,
    phoneNumbers: "1234567890",
    description: "Navigator",
    contactType: "Navigator",
  },
  {
    recordID: 20,
    givenName: "zzzzzzzzz",
    familyName: "Doe",
    thumbnailPath:
      "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
    hasThumbnail: false,
    phoneNumbers: "1234567890",
    description: "Navigator",
    contactType: "Navigator",
  },
  {
    recordID: 21,
    givenName: "zzzzzzzzz",
    familyName: "Doe",
    thumbnailPath:
      "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
    hasThumbnail: false,
    phoneNumbers: "1234567890",
    description: "Navigator",
    contactType: "Navigator",
  },
  {
    recordID: 22,
    givenName: "zzzzzzzzz",
    familyName: "Doe",
    thumbnailPath:
      "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
    hasThumbnail: false,
    phoneNumbers: "1234567890",
    description: "Navigator",
    contactType: "Navigator",
  },
  {
    recordID: 23,
    givenName: "zzzzzzzzz",
    familyName: "Doe",
    thumbnailPath:
      "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
    hasThumbnail: false,
    phoneNumbers: "1234567890",
    description: "Navigator",
    contactType: "Navigator",
  },
  {
    recordID: 24,
    givenName: "zzzzzzzzz",
    familyName: "Doe",
    thumbnailPath:
      "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
    hasThumbnail: false,
    phoneNumbers: "1234567890",
    description: "Navigator",
    contactType: "Navigator",
  },
  {
    recordID: 25,
    givenName: "zzzzzzzzz",
    familyName: "Doe",
    thumbnailPath:
      "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
    hasThumbnail: false,
    phoneNumbers: "1234567890",
    description: "Navigator",
    contactType: "Navigator",
  },
  {
    recordID: 26,
    givenName: "zzzzzzzzz 1111",
    familyName: "Doe",
    thumbnailPath:
      "https://i.pinimg.com/originals/19/db/31/19db31732931019b73bedcf17924f814.jpg",
    hasThumbnail: false,
    phoneNumbers: "1234567890",
    description: "Navigator",
    contactType: "Navigator",
  },
];

export const pendingTocs = [
  {
    name: "Jhon Doe",
    problem: "Cervical Spinal Fusion",
    date: "01/01/2022",
    navigatorName: "Actovius, Ottoma",
    trackStatus: "Pending",
  },
  {
    name: "Jhon Doe",
    problem: "Cervical Spinal Fusion",
    date: "01/01/2022",
    navigatorName: "Actovius, Ottoma",
    trackStatus: "Pending",
  },
  {
    name: "Jhon Doe",
    problem: "Cervical Spinal Fusion",
    date: "01/01/2022",
    navigatorName: "Actovius, Ottoma",
    trackStatus: "Pending",
  },
  {
    name: "Mukthahar Shaik",
    problem: "Cervical Spinal Fusion",
    date: "01/01/2022",
    navigatorName: "Actovius, Ottoma",
    trackStatus: "Pending",
  },
];
export const approved = [
  {
    name: "Tiontay Carroll",
    details: "F, 21, Procedure Date 1/14/22",
    problem: "Anterior/posterior spinal",
    isReviced: true,
    trackStatus: "Approved",
    navigatorName: "Actovius, Ottoma",
    revisedDetails: {
      revised: [
        {
          date: new Date(),
          snfValue: "GRDH Hospital",
          snfLos: "4 Days",
          irfValue: "Silver and Sand center",
          irfLos: "4 Days",
          hhValue: "Silver and Sand center",
          hhVisits: "2",
          moptValue: "GRDH Hospital",
          moptvisits: "2",
          optValue: "Forties multispeciality hospital",
          optVisits: "4",
        },
        {
          date: new Date(),
          list: ["Home without services"],
        },
      ],
    },
  },
  {
    name: "Tiontay Carroll",
    details: "F, 21, Procedure Date 1/14/22",
    problem: "Anterior/posterior spinal",
    isReviced: false,
    navigatorName: "Actovius, Ottoma",
    trackStatus: "Approved",
  },
  {
    name: "Tiontay Carroll",
    details: "F, 21, Procedure Date 1/14/22",
    problem: "Anterior/posterior spinal",
    isReviced: false,
    navigatorName: "Actovius, Ottoma",
    trackStatus: "Approved",
  },
  {
    name: "Tiontay Carroll",
    details: "F, 21, Procedure Date 1/14/22",
    problem: "Anterior/posterior spinal",
    isReviced: true,
    navigatorName: "Actovius, Ottoma",
    trackStatus: "Approved",
  },
];

export const allMessages = [
  {
    id: 1,
    positionIndex: 20,
    isUnread: true,
    images: [
      "https://rukminim1.flixcart.com/image/416/416/jq8dgnk0/poster/z/z/b/medium-baby-poster-the-boos-baby-cartoon-12x18-paper-print-be-original-imafc8harrywqghc.jpeg?q=70",
      "https://m.media-amazon.com/images/I/71hMEM1a9EL._SX425_.jpg",
    ],
    conversionName: "Mukthahar, Priyanka",
    message:
      "Patient1 fell on the floor, bleeding from the day one Patient fell on the floor, bleeding from the day one Patient fell on the floor, bleeding from the day onePatient fell on the floor, bleeding from the day one Patient fell on the floor, bleeding from the day one Patient fell on the floor, bleeding from the day one Patient fell on the floor, bleeding from the day one ",
    date: "Today 2:45 pm",
    conversionType: "ToC - John Doe",
  },
  {
    images: [
      "https://i.pinimg.com/originals/f4/ed/18/f4ed18e4f8c07a1688153de9daa5bd6c.jpg",
      "https://www.unigreet.com/wp-content/uploads/2020/09/whatsApp%EF%BB%BF-cartoon-dp-pic-822x1024.jpg",
      "https://st.depositphotos.com/1787196/1330/i/600/depositphotos_13301967-stock-photo-furry-blue-monster.jpg",
    ],
    isUnread: true,
    conversionName: "Mukthahar, Priyanka",
    message: "Patient fell on the floor, bleeding from the day one",
    date: "Today 2:45 pm",
    conversionType: "ToC - John Doe",
  },
  {
    images: [
      "https://st.depositphotos.com/1787196/1330/i/600/depositphotos_13301967-stock-photo-furry-blue-monster.jpg",
    ],
    conversionName: "Mukthahar, Priyanka",
    message: "Patient2 fell on the floor, bleeding from the day one",
    date: "Today 2:45 pm",
    conversionType: "ToC - John Doe",
  },
  {
    images: [],
    isUnread: true,
    conversionName: "Mukthahar, Priyanka",
    message: "Patient fell on the floor, bleeding from the day one",
    date: "Today 2:45 pm",
    conversionType: "ToC - John Doe",
  },
  {
    images: [],
    conversionName: "Mukthahar, Priyanka",
    message: "Patient3 fell on the floor, bleeding from the day one",
    date: "Today 2:45 pm",
    conversionType: "ToC - John Doe",
  },
  {
    images: [],
    isUnread: false,
    conversionName: "Mukthahar, Priyanka",
    message: "Patient fell on the floor, bleeding from the day one",
    date: "Today 2:45 pm",
    conversionType: "ToC - John Doe",
  },
  {
    images: [],
    isUnread: false,
    conversionName: "Mukthahar, Priyanka",
    message: "Patient fell on the floor, bleeding from the day one",
    date: "Today 2:45 pm",
    conversionType: "ToC - John Doe",
  },
  {
    images: [],
    isUnread: false,
    conversionName: "Mukthahar, Priyanka",
    message: "Patient fell on the floor, bleeding from the day one",
    date: "Today 2:45 pm",
    conversionType: "ToC - John Doe",
  },
  {
    images: [],
    isUnread: false,
    conversionName: "Mukthahar, Priyanka",
    message: "Patient fell on the floor, bleeding from the day one",
    date: "Today 2:45 pm",
    conversionType: "ToC - John Doe",
  },
  {
    images: [],
    isUnread: false,
    conversionName: "Mukthahar, Priyanka",
    message: "Patient fell on the floor, bleeding from the day one",
    date: "Today 2:45 pm",
    conversionType: "ToC - John Doe",
  },
  {
    images: [],
    isUnread: false,
    conversionName: "Mukthahar, Priyanka",
    message: "Patient fell on the floor, bleeding from the day one",
    date: "Today 2:45 pm",
    conversionType: "ToC - John Doe",
  },
  {
    images: [],
    isUnread: false,
    conversionName: "Mukthahar, Priyanka",
    message: "Patient fell on the floor, bleeding from the day one",
    date: "Today 2:45 pm",
    conversionType: "ToC - John Doe",
  },
  {
    images: [],
    isUnread: false,
    conversionName: "Mukthahar, Priyanka",
    message: "Patient fell on the floor, bleeding from the day one",
    date: "Today 2:45 pm",
    conversionType: "ToC - John Doe",
  },
  {
    images: [],
    isUnread: false,
    conversionName: "Prince",
    message: "Patient fell on the floor, bleeding from the day one",
    date: "Today 2:45 pm",
    conversionType: "ToC - John Doe",
  },
];

export const ToCDetailData = {
  patientName: "John Doe",
  patientAge: "85 Yrs",
  patientGender: "Male",
  navigatorName: "Shah RS",
  surgeryName: "Back and neck procedure of C spine, Non Fusion",
  surgeryHospitalName: "Surgery Hospital Name",
  navigatorNotes: {
    notesDesc:
      "The patient’s relatives are insisting to make him stay for morethan 5 days…",
    date: new Date(),
  },
  location: {
    los: [
      {
        location: "SNF",
        defaultValue: "1",
        defaultDays: "3",
      },
    ],
    visit: [
      {
        location: "M-OPT",
        defaultValue: "5",
        defaultDays: "3",
      },
    ],
  },
  status: "Approved",
  homeServiceChecked: true,
};

export const locationDropdownData = [
  {
    location: "SNF",
    locationNames: [
      {
        id: 1,
        name: "Silver Sand Center",
      },
      {
        id: 2,
        name: "Mayo Speciality Clinic",
      },
      {
        id: 3,
        name: "Ruby",
      },
      {
        id: 4,
        name: "React Native",
      },
      {
        id: 5,
        name: "PHP",
      },
      {
        id: 6,
        name: "Python",
      },
      {
        id: 7,
        name: "Go",
      },
      {
        id: 8,
        name: "Swift",
      },
      {
        id: 9,
        name: "C",
      },
      {
        id: 10,
        name: "C++",
      },
      {
        id: 11,
        name: "TS",
      },
      {
        id: 12,
        name: "JS",
      },
    ],
  },
  {
    location: "IRF",
    locationNames: [
      {
        id: 1,
        name: "Silver Sand Center",
      },
      {
        id: 2,
        name: "Mayo Speciality Clinic",
      },
      {
        id: 3,
        name: "Ruby",
      },
      {
        id: 4,
        name: "React Native",
      },
      {
        id: 5,
        name: "PHP",
      },
      {
        id: 6,
        name: "Python",
      },
      {
        id: 7,
        name: "Go",
      },
      {
        id: 8,
        name: "Swift",
      },
      {
        id: 9,
        name: "C",
      },
      {
        id: 10,
        name: "C++",
      },
      {
        id: 11,
        name: "TS",
      },
      {
        id: 12,
        name: "JS",
      },
    ],
  },

  {
    location: "HH",
    locationNames: [
      {
        id: 1,
        name: "Silver Sand Center",
      },
      {
        id: 2,
        name: "Mayo Speciality Clinic",
      },
      {
        id: 3,
        name: "Ruby",
      },
      {
        id: 4,
        name: "React Native",
      },
      {
        id: 5,
        name: "PHP",
      },
      {
        id: 6,
        name: "Python",
      },
      {
        id: 7,
        name: "Go",
      },
      {
        id: 8,
        name: "Swift",
      },
      {
        id: 9,
        name: "C",
      },
      {
        id: 10,
        name: "C++",
      },
      {
        id: 11,
        name: "TS",
      },
      {
        id: 12,
        name: "JS",
      },
    ],
  },
  {
    location: "M-OPT",
    locationNames: [
      {
        id: 1,
        name: "Silver Sand Center",
      },
      {
        id: 2,
        name: "Mayo Speciality Clinic",
      },
      {
        id: 3,
        name: "Ruby",
      },
      {
        id: 4,
        name: "React Native",
      },
      {
        id: 5,
        name: "PHP",
      },
      {
        id: 6,
        name: "Python",
      },
      {
        id: 7,
        name: "Go",
      },
      {
        id: 8,
        name: "Swift",
      },
      {
        id: 9,
        name: "C",
      },
      {
        id: 10,
        name: "C++",
      },
      {
        id: 11,
        name: "TS",
      },
      {
        id: 12,
        name: "JS",
      },
    ],
  },
  {
    location: "OPT",
    locationNames: [
      {
        id: 1,
        name: "Silver Sand Center",
      },
      {
        id: 2,
        name: "Mayo Speciality Clinic",
      },
      {
        id: 3,
        name: "Ruby",
      },
      {
        id: 4,
        name: "React Native",
      },
      {
        id: 5,
        name: "PHP",
      },
      {
        id: 6,
        name: "Python",
      },
      {
        id: 7,
        name: "Go",
      },
      {
        id: 8,
        name: "Swift",
      },
      {
        id: 9,
        name: "C",
      },
      {
        id: 10,
        name: "C++",
      },
      {
        id: 11,
        name: "TS",
      },
      {
        id: 12,
        name: "JS",
      },
    ],
  },
];

export const locationNames = [
  {
    ID: 9125,
    FirstName: "Freddy",
    LastName: "Testerson",
    ProviderName: "Freddy Testerson MD",
    ProviderPhone: "54754957485",
  },
  {
    ID: 9126,
    FirstName: "Freddy",
    LastName: "Testerson",
    ProviderName: "Freddy hkrejtr MD",
    ProviderPhone: "54754957485",
  },
  {
    ID: 9127,
    FirstName: "Freddy",
    LastName: "Testerson",
    ProviderName: "Freddy Freddy MD",
    ProviderPhone: "54754957485",
  },
  {
    ID: 9128,
    FirstName: "Freddy",
    LastName: "Testerson",
    ProviderName: "Freddy SSSf MD",
    ProviderPhone: "54754957485",
  },
];

export const chatMessages = [
  {
    _id: 1,
    message: {
      type: "TEXT",
      content: "How are you  Mr Aiden?",
    },
    createdAt: "2022-02-24T11:50:42.468Z",
    user: {
      _id: 1,
      name: "Dr. Mukthahar",
      avatar: "https://placeimg.com/140/140/any",
    },
  },
  {
    _id: 2,
    message: {
      type: "TEXT",
      content: "I how you are well?",
    },
    createdAt: "2022-02-24T11:50:42.468Z",
    user: {
      _id: 1,
      name: "Dr. Mukthahar",
      avatar: "https://placeimg.com/140/140/any",
    },
  },
  {
    _id: 3,
    text: "Doctor, I am feeling better. I had a severe backpain though.",
    message: {
      type: "TEXT",
      content: "I how you are well?",
    },
    createdAt: "2022-02-24T11:45:42.468Z",
    user: {
      _id: 2,
      name: "Aiden",
      avatar: "https://placeimg.com/140/140/any",
    },
  },
  {
    _id: 4,
    text: "I had a severe backpain though.",
    message: {
      type: "TEXT",
      content: "I how you are well?",
    },
    createdAt: "2022-02-24T11:45:42.468Z",
    user: {
      _id: 2,
      name: "Aiden",
      avatar: "https://placeimg.com/140/140/any",
    },
  },
  {
    _id: 5,
    text: "Please pay a visit to the hospital so that I can do an examination ",
    message: {
      type: "TEXT",
      content: "I how you are well?",
    },
    createdAt: "2022-02-25T11:40:42.468Z",
    user: {
      _id: 1,
      name: "Dr. Mukthahar",
      avatar: "https://placeimg.com/140/140/any",
    },
  },
  {
    _id: 6,
    text: "okkk doctor",
    message: {
      type: "TEXT",
      content: "I how you are well?",
    },
    createdAt: "2022-02-25T11:35:42.468Z",
    user: {
      _id: 2,
      name: "Aiden",
      avatar: "https://placeimg.com/140/140/any",
    },
  },
  {
    _id: 7,
    text: "How are you  Mr Aiden?",
    message: {
      type: "TEXT",
      content: "I how you are well?",
    },
    createdAt: "2022-02-24T11:50:42.468Z",
    user: {
      _id: 1,
      name: "Dr. Mukthahar",
      avatar: "https://placeimg.com/140/140/any",
    },
  },
  {
    _id: 8,
    text: "I how you are well?",
    message: {
      type: "TEXT",
      content: "I how you are well?",
    },
    createdAt: "2022-02-24T11:50:42.468Z",
    user: {
      _id: 1,
      name: "Dr. Mukthahar",
      avatar: "https://placeimg.com/140/140/any",
    },
  },
  {
    _id: 9,
    text: "Doctor, I am feeling better. I had a severe backpain though.",
    message: {
      type: "TEXT",
      content: "I how you are well?",
    },
    createdAt: "2022-02-24T11:45:42.468Z",
    user: {
      _id: 2,
      name: "Aiden",
      avatar: "https://placeimg.com/140/140/any",
    },
  },
  {
    _id: "112jdskfjksadjfk",
    text: "I had a severe backpain though.",
    message: {
      type: "TEXT",
      content: "I how you are well?",
    },
    createdAt: "2022-02-24T11:45:42.468Z",
    user: {
      _id: 2,
      name: "Aiden",
      avatar: "https://placeimg.com/140/140/any",
    },
  },
  {
    _id: 11,
    text: "",
    message: {
      type: "IMAGE",
      content: "https://placeimg.com/140/140/any",
    },
    createdAt: "2022-02-27T11:40:42.468Z",
    user: {
      _id: 1,
      name: "Dr. Mukthahar",
      avatar: "https://placeimg.com/140/140/any",
    },
  },
  {
    _id: 12,
    text: "okkk doctor",
    message: {
      type: "TEXT",
      content: "I how you are well?",
    },
    createdAt: "2022-02-28T11:35:42.468Z",
    user: {
      _id: 2,
      name: "Aiden",
      avatar: "https://placeimg.com/140/140/any",
    },
  },
  {
    _id: "dfkasjfdajsk",
    text: "okkk doctor",
    message: {
      type: "IMAGE",
      content:
        "https://rukminim1.flixcart.com/image/416/416/jq8dgnk0/poster/z/z/b/medium-baby-poster-the-boos-baby-cartoon-12x18-paper-print-be-original-imafc8harrywqghc.jpeg?q=70",
    },
    createdAt: "2022-02-28T11:35:42.468Z",
    user: {
      _id: 2,
      name: "Aiden",
      avatar: "https://placeimg.com/140/140/any",
    },
  },
];

export const NotificationsData = [
  {
    id: 1,
    message: "Sarah Will’s ToC need your approval",
    Date: new Date(),
    type: "APPROVETOC",
    highlightedText: ["Sarah Will’s ToC"],
    isRead: false,
  },
  {
    id: 2,
    message: "Shah, RS Navigator has sent you a message",
    Date: new Date(),
    type: "MESSAGE",
    highlightedText: ["Shah,", "RS Navigator"],
    isRead: true,
  },
  {
    id: 3,
    message: "John Doe is staying longer than the prescribed ToC",
    Date: new Date(),
    type: "OFFTRACKTOC",
    highlightedText: ["John Doe"],
    isRead: false,
  },
  {
    id: 1,
    message: "Sarah Will’s ToC need your approval",
    Date: new Date(),
    type: "APPROVETOC",
    highlightedText: ["Sarah Will’s ToC"],
    isRead: false,
  },
  {
    id: 2,
    message: "Shah, RS Navigator has sent you a message",
    Date: new Date(),
    type: "MESSAGE",
    highlightedText: ["Shah,", "RS Navigator"],
    isRead: true,
  },
  {
    id: 3,
    message: "John Doe is staying longer than the prescribed ToC",
    Date: new Date(),
    type: "OFFTRACKTOC",
    highlightedText: ["John Doe"],
    isRead: false,
  },
  {
    id: 1,
    message: "Sarah Will’s ToC need your approval",
    Date: new Date(),
    type: "APPROVETOC",
    highlightedText: ["Sarah Will’s ToC"],
    isRead: false,
  },
  {
    id: 2,
    message: "Shah, RS Navigator has sent you a message",
    Date: new Date(),
    type: "MESSAGE",
    highlightedText: ["Shah,", "RS Navigator"],
    isRead: true,
  },
  {
    id: 3,
    message: "John Doe is staying longer than the prescribed ToC",
    Date: new Date(),
    type: "OFFTRACKTOC",
    highlightedText: ["John Doe"],
    isRead: false,
  },
  {
    id: 1,
    message: "Sarah Will’s ToC need your approval",
    Date: new Date(),
    type: "APPROVETOC",
    highlightedText: ["Sarah Will’s ToC"],
    isRead: false,
  },
  {
    id: 2,
    message: "Shah, RS Navigator has sent you a message",
    Date: new Date(),
    type: "MESSAGE",
    highlightedText: ["Shah,", "RS Navigator"],
    isRead: true,
  },
  {
    id: 3,
    message: "John Doe is staying longer than the prescribed ToC",
    Date: new Date(),
    type: "OFFTRACKTOC",
    highlightedText: ["John Doe"],
    isRead: false,
  },
  {
    id: 1,
    message: "Sarah Will’s ToC need your approval",
    Date: new Date(),
    type: "APPROVETOC",
    highlightedText: ["Sarah Will’s ToC"],
    isRead: false,
  },
  {
    id: 2,
    message: "Shah, RS Navigator has sent you a message",
    Date: new Date(),
    type: "MESSAGE",
    highlightedText: ["Shah,", "RS Navigator"],
    isRead: true,
  },
  {
    id: 3,
    message: "John Doe is staying longer than the prescribed ToC",
    Date: new Date(),
    type: "OFFTRACKTOC",
    highlightedText: ["John Doe"],
    isRead: false,
  },
  {
    id: 1,
    message: "Sarah Will’s ToC need your approval",
    Date: new Date(),
    type: "APPROVETOC",
    highlightedText: ["Sarah Will’s ToC"],
    isRead: false,
  },
  {
    id: 2,
    message: "Shah, RS Navigator has sent you a message",
    Date: new Date(),
    type: "MESSAGE",
    highlightedText: ["Shah,", "RS Navigator"],
    isRead: true,
  },
  {
    id: 3,
    message: "John Doe is staying longer than the prescribed ToC",
    Date: new Date(),
    type: "OFFTRACKTOC",
    highlightedText: ["John Doe"],
    isRead: false,
  },
  {
    id: 1,
    message: "Sarah Will’s ToC need your approval",
    Date: new Date(),
    type: "APPROVETOC",
    highlightedText: ["Sarah Will’s ToC"],
    isRead: false,
  },
  {
    id: 2,
    message: "Shah, RS Navigator has sent you a message",
    Date: new Date(),
    type: "MESSAGE",
    highlightedText: ["Shah,", "RS Navigator"],
    isRead: true,
  },
  {
    id: 3,
    message: "John Doe is staying longer than the prescribed ToC",
    Date: new Date(),
    type: "OFFTRACKTOC",
    highlightedText: ["John Doe"],
    isRead: false,
  },
];

export const TOCDetail = [
  {
    id: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    intakeID: 0,
    clientID: 0,
    providerID: 0,
    facilityID: 0,
    noteCareManager:
      "The patient’s relatives are insisting to make him stay for more than 5 days…",
    notePhysician: "string",
    electronicSignatureKey: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    electronicSignatureDate: "2022-03-31T11:29:24.566Z",
    electronicSignatureUser: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    version: 0,
    recordCreated: "2022-03-31T11:29:24.566Z",
    recordCreatedString: "string",
    recordCreatedBy: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    recordUpdated: "2022-03-31T11:29:24.566Z",
    recordUpdatedBy: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    sentToDischargePlanner: true,
    sentToDischargePlannerDate: "2022-03-31T11:29:24.566Z",
    sentToDischargePlannerBy: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    sentToDischargePlannerByFormattedName: "string",
    surgeon: {
      id: 0,
      clientID: 0,
      firstName: "string",
      middleName: "string",
      lastName: "string",
      email: "string",
      genderID: 0,
      tin: "string",
      dob: "2022-03-31T11:29:24.567Z",
      prefix: 0,
      suffix: 0,
      credentials: "string",
      providerName: "string",
      providerID: "string",
      isFacility: true,
      providerType: 0,
      specialtyType: 0,
      specialtyName: "string",
      isPCP: true,
      isActive: true,
      isAcceptingNewPatients: true,
      providerAddress1: "string",
      providerAddress2: "string",
      providerCity: "string",
      providerState: "string",
      providerZip: "string",
      providerPhone: "string",
      providerCell: "string",
      providerFax: "string",
      providerHome: "string",
      npi: "string",
      externalProviderID: "string",
      practiceID: 0,
      providerNotes: "string",
      ccn: "string",
      recordCreated: "2022-03-31T11:29:24.567Z",
      recordCreatedBy: "string",
      recordUpdated: "2022-03-31T11:29:24.567Z",
      recordUpdatedBy: "string",
      preferredProvider: true,
      lastDeactivatedReasonId: 0,
      lastDeactivatedUserId: "string",
      admittingPhysician: "string",
      admittingPhysicianID: "string",
      isExactMatch: true,
    },
    facility: {
      id: 0,
      clientID: 0,
      firstName: "string",
      middleName: "string",
      lastName: "string",
      email: "string",
      genderID: 0,
      tin: "string",
      dob: "2022-03-31T11:29:24.567Z",
      prefix: 0,
      suffix: 0,
      credentials: "string",
      providerName:
        "Surgery Hospital Name hjgfjlgkdfhglfjkdl fdkfhkdlsfldgdfkgfdgfhkl ",
      providerID: "string",
      isFacility: true,
      providerType: 0,
      specialtyType: 0,
      specialtyName: "string",
      isPCP: true,
      isActive: true,
      isAcceptingNewPatients: true,
      providerAddress1: "string",
      providerAddress2: "string",
      providerCity: "string",
      providerState: "string",
      providerZip: "string",
      providerPhone: "string",
      providerCell: "string",
      providerFax: "string",
      providerHome: "string",
      npi: "string",
      externalProviderID: "string",
      practiceID: 0,
      providerNotes: "string",
      ccn: "string",
      recordCreated: "2022-03-31T11:29:24.567Z",
      recordCreatedBy: "string",
      recordUpdated: "2022-03-31T11:29:24.567Z",
      recordUpdatedBy: "string",
      preferredProvider: true,
      lastDeactivatedReasonId: 0,
      lastDeactivatedUserId: "string",
      admittingPhysician: "string",
      admittingPhysicianID: "string",
      isExactMatch: true,
    },
    reviewedWithProvider: false,
    reviewedWithProviderDate: "2022-03-31T11:29:24.567Z",
    reviewedWithProviderBy: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    reviewedWithProviderByFormattedName: "string",
    patient: {
      id: 0,
      firstName: "John",
      lastName: "Doe",
      dob: "1998-03-31T11:29:24.567Z",
      mbi: "string",
      medicareID: "string",
      isActive: true,
      lastDeactivateReasonId: 0,
      lastDeactivateUserId: "string",
      gender: "male",
      zip: "string",
      searchText: "string",
      mbiEffectiveDate: "2022-03-31T11:29:24.567Z",
      mrn: "string",
      genderID: 0,
      genderName: "string",
      primaryCarePhysician: {
        id: 0,
        clientID: 0,
        firstName: "string",
        middleName: "string",
        lastName: "string",
        email: "string",
        genderID: 0,
        tin: "string",
        dob: "2022-03-31T11:29:24.567Z",
        prefix: 0,
        suffix: 0,
        credentials: "string",
        providerName: "string",
        providerID: "string",
        isFacility: true,
        providerType: 0,
        specialtyType: 0,
        specialtyName: "string",
        isPCP: true,
        isActive: true,
        isAcceptingNewPatients: true,
        providerAddress1: "string",
        providerAddress2: "string",
        providerCity: "string",
        providerState: "string",
        providerZip: "string",
        providerPhone: "string",
        providerCell: "string",
        providerFax: "string",
        providerHome: "string",
        npi: "string",
        externalProviderID: "string",
        practiceID: 0,
        providerNotes: "string",
        ccn: "string",
        recordCreated: "2022-03-31T11:29:24.567Z",
        recordCreatedBy: "string",
        recordUpdated: "2022-03-31T11:29:24.567Z",
        recordUpdatedBy: "string",
        preferredProvider: true,
        lastDeactivatedReasonId: 0,
        lastDeactivatedUserId: "string",
        admittingPhysician: "string",
        admittingPhysicianID: "string",
        isExactMatch: true,
      },
      externalPatientID: "string",
      coachRelationship: "string",
      coachName: "string",
      coachPhone: "string",
      coachEmail: "string",
      phoneWork: "string",
      phoneWorkExt: "string",
      phoneCell: "string",
      phoneHome: "string",
      preferredPhone: "string",
      preferredName: "string",
      completedYears: "string",
      consentToContactCoach: true,
      advancedDirectives: true,
    },
    intake: {
      id: 0,
      patientID: 0,
      clientID: 0,
      programID: 0,
      medSurg: 0,
      surgeryCategoryID: 0,
      episodeID: 0,
      episodeLongName: "Back and neck procedure of C spine, Non Fusion",
      surgeryDate: "2022-03-31T11:29:24.567Z",
      admitDate: "2022-03-31T11:29:24.567Z",
      intakeStatusName: "string",
      intakeStatusID: 0,
      partialIntake: true,
      surgeryDischargeDate: "2022-03-31T11:29:24.567Z",
      surgerySite: "string",
      surgerySide: "string",
      programEnrollmentDate: "2022-03-31T11:29:24.567Z",
      programDischargeDate: "2022-03-31T11:29:24.567Z",
      primaryCareManagerID: "string",
      primaryCareManagerName: "Shah RS",
      primaryCareManagerPhone: "string",
      bnl: 0,
      bnlDate: "2022-03-31T11:29:24.567Z",
      plannedUnplanned: 0,
      recordCreated: "2022-03-31T11:29:24.567Z",
      recordCreatedBy: "string",
      recordUpdated: "2022-03-31T11:29:24.567Z",
      recordUpdatedBy: "string",
      facilityID: 0,
      surgeonID: 0,
      dischargePhysicianID: 0,
      surgeryOrAdmitDateChangeNotes: "string",
      episodeChangeNotes: "string",
      practiceID: 0,
      dI_IntakeImported: true,
      dI_IntakeImportDate: "2022-03-31T11:29:24.567Z",
      dI_IntakeImportBatchCode: "string",
      patient: {
        id: 0,
        firstName: "string",
        lastName: "string",
        dob: "2022-03-31T11:29:24.567Z",
        mbi: "string",
        medicareID: "string",
        isActive: true,
        lastDeactivateReasonId: 0,
        lastDeactivateUserId: "string",
        gender: "string",
        zip: "string",
        searchText: "string",
        mbiEffectiveDate: "2022-03-31T11:29:24.567Z",
        mrn: "string",
        genderID: 0,
        genderName: "string",
        primaryCarePhysician: {
          id: 0,
          clientID: 0,
          firstName: "string",
          middleName: "string",
          lastName: "string",
          email: "string",
          genderID: 0,
          tin: "string",
          dob: "2022-03-31T11:29:24.567Z",
          prefix: 0,
          suffix: 0,
          credentials: "string",
          providerName: "string",
          providerID: "string",
          isFacility: true,
          providerType: 0,
          specialtyType: 0,
          specialtyName: "string",
          isPCP: true,
          isActive: true,
          isAcceptingNewPatients: true,
          providerAddress1: "string",
          providerAddress2: "string",
          providerCity: "string",
          providerState: "string",
          providerZip: "string",
          providerPhone: "string",
          providerCell: "string",
          providerFax: "string",
          providerHome: "string",
          npi: "string",
          externalProviderID: "string",
          practiceID: 0,
          providerNotes: "string",
          ccn: "string",
          recordCreated: "2022-03-31T11:29:24.567Z",
          recordCreatedBy: "string",
          recordUpdated: "2022-03-31T11:29:24.567Z",
          recordUpdatedBy: "string",
          preferredProvider: true,
          lastDeactivatedReasonId: 0,
          lastDeactivatedUserId: "string",
          admittingPhysician: "string",
          admittingPhysicianID: "string",
          isExactMatch: true,
        },
        externalPatientID: "string",
        coachRelationship: "string",
        coachName: "string",
        coachPhone: "string",
        coachEmail: "string",
        phoneWork: "string",
        phoneWorkExt: "string",
        phoneCell: "string",
        phoneHome: "string",
        preferredPhone: "string",
        preferredName: "string",
        completedYears: "string",
        consentToContactCoach: true,
        advancedDirectives: true,
      },
      insuranceType: "string",
      otherInsuranceID: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      episodeTypeID: 0,
      programTypeShortName: "string",
      coachID: 0,
      consentToContact: true,
      onsetDate: "2022-03-31T11:29:24.567Z",
      episodeRefDate: "2022-03-31T11:29:24.567Z",
      dischargeStatusID: 0,
      program: {
        id: 0,
        clientID: 0,
        longName: "string",
        shortName: "string",
        programStartDate: "2022-03-31T11:29:24.567Z",
        programEndDate: "2022-03-31T11:29:24.567Z",
        isVolunatary: 0,
        inpatientEpisodes: 0,
        outPatientEpisodes: 0,
        recordCreated: "2022-03-31T11:29:24.567Z",
        recordCreatedBy: "string",
        recordUpdated: "2022-03-31T11:29:24.567Z",
        recordUpdatedBy: "string",
        programTypeId: 0,
        isActive: true,
      },
      episode: {
        id: 0,
        clientID: 0,
        surgeryCategoryID: 0,
        longName: "string",
        shortName: "string",
        programID: 0,
        episodeType: "string",
        episodeStartDate: "2022-03-31T11:29:24.567Z",
        episodeEndDate: "2022-03-31T11:29:24.567Z",
        episodeDRG1: "string",
        episodeDRG2: "string",
        episodeDRG3: "string",
        episodeDRG4: "string",
        episodeDRG5: "string",
        episodeDRG6: "string",
        episodeDRG7: "string",
        episodeDRG8: "string",
        recordCreated: "2022-03-31T11:29:24.567Z",
        recordCreatedBy: "string",
        recordUpdated: "2022-03-31T11:29:24.567Z",
        recordUpdatedBy: "string",
        isActive: true,
      },
      siteSideName: "string",
      advancedDirectives: true,
      episodeTypeName: "string",
      episodeCareName: "string",
      episodeSettingName: "string",
    },
    transitionOfCareItems: [
      {
        id: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        tTransitionOfCareID: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        pacTypeID: 0,
        pacTypeName: "SNF",
        providerID: 1,
        providerName: "Testing testing testing",
        providerPhone: "string",
        anticipatedAdmitDisplayDate: "string",
        anticipatedDischargeDisplayDate: "string",
        targetLOS: 3,
        recordCreated: "2022-03-31T11:29:24.567Z",
        recordCreatedBy: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        recordUpdated: "2022-03-31T11:29:24.567Z",
        recordUpdatedBy: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        validFromUTC: "2022-03-31T11:29:24.567Z",
        validToUTC: "2022-03-31T11:29:24.567Z",
      },
    ],
    eSign: true,
    workflowDetailID: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    anticipatedAcuteLOS: 4,
    reviewedWithProviderFormattedDate: "string",
    sentToDischargePlannerFormattedDate: "string",
    validFromUTC: "2022-03-31T11:29:24.567Z",
    validToUTC: "2022-03-31T11:29:24.567Z",
  },
];

export const notificationData = {
  notificationDetails: [
    {
      id: 1,
      ownerUserId: "123",
      eventDesc: "Mukthahar shaik as sent you a message.",
      eventType: "NEW_MESSAGE",
      actionEntityId: 1,
      isActive: true,
      createdOn: new Date(),
    },
  ],
  responseStatus: "success",
};

export const tocListData = {
  Count: {
    Pending: 3,
    Approved: 10,
  },
  ToCList: {
    Pending: [
      {
        PatientName: "StrokeDev",
        PatientDOB: "21-03-1963 00:00:00",
        PatientGender: "M",
        NavigatorFirstName: "Test",
        NavigatorLastName: "Intake1111-2002 Navigator",
        ProcedureDescription: "AMI Test",
        ProcedureDate: "2018-11-27 05:00:00.0000000",
        IntakeID: 10735,
        TocCreatedDate: "2022-01-05 21:07:20.3741965",
        Status: "Approved",
        revision: [
          {
            ToC_ID: "EC489B46-11D8-4466-F1AE-08D9D08F2EF7",
            CreatedDateTime: "2022-04-12 13:05:10.4252050",
            Version: 2,
            TransitionOfCareItems: [
              {
                ProviderID: 9113,
                ProviderName: "dsf",
                PacTypeName: "IRF",
                TargetLOS: 1,
              },
              {
                ProviderID: 9100,
                ProviderName: "James Sperey",
                PacTypeName: "HH",
                TargetLOS: 10,
              },
            ],
            AnticipatedAcuteLos: 1,
          },
          {
            ToC_ID: "29ECF3B6-A244-4924-F1AD-08D9D08F2EF7",
            CreatedDateTime: "2022-01-05 21:06:20.3840000",
            Version: 1,
            TransitionOfCareItems: [
              {
                ProviderID: 9106,
                ProviderName: "Apple Rehab - Tulsa",
                PacTypeName: "PACIPREHAB",
                TargetLOS: 5,
              },
            ],
            AnticipatedAcuteLos: 1,
          },
        ],
      },
      {
        PatientName: "PCICABGDev",
        PatientDOB: "09-03-2016 00:00:00",
        PatientGender: "F",
        NavigatorFirstName: "Test",
        NavigatorLastName: "Intake1111-2002",
        ProcedureDescription: "Percutaneous coronary intervention",
        ProcedureDate: "2018-11-14 00:00:00.0000000",
        IntakeID: 10749,
        TocCreatedDate: "2021-12-10 16:43:33.8790000",
        Status: "Approved",
        revision: [
          {
            ToC_ID: "EE0BCD49-CA34-413B-D25A-08D9BBFC34A6",
            CreatedDateTime: "2021-12-10 16:44:58.3620000",
            Version: 1,
            TransitionOfCareItems: [
              {
                ProviderID: 9107,
                ProviderName: "Apple Rehab - Waco",
                PacTypeName: "IRF",
                TargetLOS: 3,
              },
            ],
            AnticipatedAcuteLos: 2,
          },
        ],
      },
      {
        PatientName: "StrokeDev",
        PatientDOB: "21-03-1963 00:00:00",
        PatientGender: "F",
        NavigatorFirstName: "Huy",
        NavigatorLastName: "1111-2002",
        ProcedureDescription: "AMI Test",
        ProcedureDate: null,
        IntakeID: 41813,
        TocCreatedDate: "2022-01-05 14:23:16.1336877",
        Status: "Approved",
        revision: [
          {
            ToC_ID: "16A58572-FE77-463A-A1F5-08D9CFD56C28",
            CreatedDateTime: "2022-04-12 01:20:20.9116621",
            Version: 1,
            TransitionOfCareItems: [
              {
                ProviderID: 9106,
                ProviderName: "Apple Rehab - Tulsa",
                PacTypeName: "IRF",
                TargetLOS: 2,
              },
            ],
            AnticipatedAcuteLos: 1,
          },
        ],
      },
    ],
    Approved: [
      {
        PatientName: "StrokeDev",
        PatientDOB: "21-03-1963 00:00:00",
        PatientGender: "M",
        NavigatorFirstName: "Test",
        NavigatorLastName: "Intake1111-2002",
        ProcedureDescription: "AMI Test",
        ProcedureDate: "2018-11-27 05:00:00.0000000",
        IntakeID: 10735,
        TocCreatedDate: "2022-01-05 21:07:20.3741965",
        Status: "Approved",
        revision: [
          {
            ToC_ID: "EC489B46-11D8-4466-F1AE-08D9D08F2EF7",
            CreatedDateTime: "2022-04-12 13:05:10.4252050",
            Version: 2,
            TransitionOfCareItems: [
              {
                ProviderID: 9113,
                ProviderName: "dsf",
                PacTypeName: "IRF",
                TargetLOS: 1,
              },
              {
                ProviderID: 9100,
                ProviderName: "James Sperey",
                PacTypeName: "HH",
                TargetLOS: 10,
              },
            ],
            AnticipatedAcuteLos: 1,
          },
          {
            ToC_ID: "29ECF3B6-A244-4924-F1AD-08D9D08F2EF7",
            CreatedDateTime: "2022-01-05 21:06:20.3840000",
            Version: 1,
            TransitionOfCareItems: [
              {
                ProviderID: 9106,
                ProviderName: "Apple Rehab - Tulsa",
                PacTypeName: "PACIPREHAB",
                TargetLOS: 5,
              },
            ],
            AnticipatedAcuteLos: 1,
          },
        ],
      },
      {
        PatientName: "PCICABGDev",
        PatientDOB: "09-03-2016 00:00:00",
        PatientGender: "F",
        NavigatorFirstName: "Test",
        NavigatorLastName: "Intake1111-2002",
        ProcedureDescription: "Percutaneous coronary intervention",
        ProcedureDate: "2018-11-14 00:00:00.0000000",
        IntakeID: 10749,
        TocCreatedDate: "2021-12-10 16:43:33.8790000",
        Status: "Approved",
        revision: [
          {
            ToC_ID: "EE0BCD49-CA34-413B-D25A-08D9BBFC34A6",
            CreatedDateTime: "2021-12-10 16:44:58.3620000",
            Version: 1,
            TransitionOfCareItems: [
              {
                ProviderID: 9107,
                ProviderName: "Apple Rehab - Waco",
                PacTypeName: "IRF",
                TargetLOS: 3,
              },
            ],
            AnticipatedAcuteLos: 2,
          },
        ],
      },
      {
        PatientName: "StrokeDev",
        PatientDOB: "21-03-1963 00:00:00",
        PatientGender: "F",
        NavigatorFirstName: "Huy",
        NavigatorLastName: "1111-2002",
        ProcedureDescription: "AMI Test",
        ProcedureDate: null,
        IntakeID: 41813,
        TocCreatedDate: "2022-01-05 14:23:16.1336877",
        Status: "Approved",
        revision: [
          {
            ToC_ID: "16A58572-FE77-463A-A1F5-08D9CFD56C28",
            CreatedDateTime: "2022-04-12 01:20:20.9116621",
            Version: 1,
            TransitionOfCareItems: [
              {
                ProviderID: 9106,
                ProviderName: "Apple Rehab - Tulsa",
                PacTypeName: "IRF",
                TargetLOS: 2,
              },
            ],
            AnticipatedAcuteLos: 1,
          },
        ],
      },
      {
        PatientName: "Amy 'Charlene''Ball",
        PatientDOB: "22-10-2020 00:00:00",
        PatientGender: "M",
        NavigatorFirstName: "Michael",
        NavigatorLastName: "Brennan",
        ProcedureDescription: "Michael Test",
        ProcedureDate: "2020-11-10 05:00:00.0000000",
        IntakeID: 42650,
        TocCreatedDate: "2021-12-14 18:29:04.3950000",
        Status: "Approved",
        revision: [
          {
            ToC_ID: "37A53921-4233-41A7-2CA2-08D9BF2F726E",
            CreatedDateTime: "2022-04-12 01:00:52.1507420",
            Version: 2,
            TransitionOfCareItems: [
              {
                ProviderID: 9106,
                ProviderName: "Apple Rehab - Tulsa",
                PacTypeName: "SNF",
                TargetLOS: 10,
              },
            ],
            AnticipatedAcuteLos: 1,
          },
          {
            ToC_ID: "53B2D919-85AF-402E-2CA1-08D9BF2F726E",
            CreatedDateTime: "2021-12-14 06:28:00.0000000",
            Version: 1,
            TransitionOfCareItems: [
              {
                ProviderID: 8880,
                ProviderName: "Greater Metro Hospital",
                PacTypeName: "SNF",
                TargetLOS: 5,
              },
            ],
            AnticipatedAcuteLos: 1,
          },
        ],
      },
      {
        PatientName: "VickyClark",
        PatientDOB: "01-11-1922 00:00:00",
        PatientGender: "M",
        NavigatorFirstName: "Joe",
        NavigatorLastName: "1111-2002",
        ProcedureDescription: "Bariatric",
        ProcedureDate: "2021-12-21 05:00:00.0000000",
        IntakeID: 42685,
        TocCreatedDate: "2021-12-14 15:21:41.4010000",
        Status: "Approved",
        revision: [
          {
            ToC_ID: "5C3967FB-09CF-4561-A7F9-08D9BF156E3E",
            CreatedDateTime: "2021-12-14 15:22:43.7950000",
            Version: 1,
            TransitionOfCareItems: [
              {
                ProviderID: 9106,
                ProviderName: "Apple Rehab - Tulsa",
                PacTypeName: "IRF",
                TargetLOS: 5,
              },
            ],
            AnticipatedAcuteLos: 2,
          },
        ],
      },
      {
        PatientName: "MaryLangman",
        PatientDOB: "27-03-1960 00:00:00",
        PatientGender: "M",
        NavigatorFirstName: "DebbieM",
        NavigatorLastName: "1111-2002",
        ProcedureDescription: "Bariatric",
        ProcedureDate: null,
        IntakeID: 42694,
        TocCreatedDate: "2022-01-17 14:13:03.4120000",
        Status: "Approved",
        revision: [
          {
            ToC_ID: "27E4F2AA-3353-4DBB-B245-08D9D9C379C0",
            CreatedDateTime: "2022-01-17 20:15:40.6270000",
            Version: 6,
            TransitionOfCareItems: [
              {
                ProviderID: 9106,
                ProviderName: "Apple Rehab - Tulsa",
                PacTypeName: "IRF",
                TargetLOS: 1,
              },
            ],
            AnticipatedAcuteLos: 1,
          },
          {
            ToC_ID: "8756415E-856E-42B7-A1F0-08D9CFD56C28",
            CreatedDateTime: "2022-01-04 23:00:10.5890000",
            Version: 3,
            TransitionOfCareItems: [
              {
                ProviderID: 9106,
                ProviderName: "Apple Rehab - Tulsa",
                PacTypeName: "PACIPREHAB",
                TargetLOS: 20,
              },
            ],
            AnticipatedAcuteLos: 5,
          },
          {
            ToC_ID: "03C1D052-3825-4097-A1EF-08D9CFD56C28",
            CreatedDateTime: "2022-01-04 22:58:26.5340000",
            Version: 2,
            TransitionOfCareItems: [
              {
                ProviderID: 9125,
                ProviderName: "Freddy Testerson MD",
                PacTypeName: "HH",
                TargetLOS: 2,
              },
            ],
            AnticipatedAcuteLos: 2,
          },
        ],
      },
      {
        PatientName: "CarlChipmunk",
        PatientDOB: "14-10-1947 00:00:00",
        PatientGender: "M",
        NavigatorFirstName: "DebbieM",
        NavigatorLastName: "1111-2002",
        ProcedureDescription: "AMI Test",
        ProcedureDate: "2021-11-17 05:00:00.0000000",
        IntakeID: 42757,
        TocCreatedDate: "2021-12-03 16:54:42.3610000",
        Status: "Approved",
        revision: [
          {
            ToC_ID: "C71E1FB2-7F2B-4B7D-903C-08D9B67D9A31",
            CreatedDateTime: "2021-12-03 16:56:00.0000000",
            Version: 4,
            TransitionOfCareItems: [
              {
                ProviderID: 9106,
                ProviderName: "Apple Rehab - Tulsa",
                PacTypeName: "IRF",
                TargetLOS: 4,
              },
            ],
            AnticipatedAcuteLos: 1,
          },
          {
            ToC_ID: "3814E5E0-EEB2-4251-863D-08D9B5FD795C",
            CreatedDateTime: "2021-12-03 16:53:54.0900000",
            Version: 3,
            TransitionOfCareItems: [
              {
                ProviderID: 9106,
                ProviderName: "Apple Rehab - Tulsa",
                PacTypeName: "PACIPREHAB",
                TargetLOS: 5,
              },
            ],
            AnticipatedAcuteLos: 1,
          },
          {
            ToC_ID: "A8C0F692-738A-45BC-35F2-08D9AB926CE8",
            CreatedDateTime: "2021-11-19 20:15:14.7750000",
            Version: 2,
            TransitionOfCareItems: [
              {
                ProviderID: 9106,
                ProviderName: "Apple Rehab - Tulsa",
                PacTypeName: "SNF",
                TargetLOS: 4,
              },
              {
                ProviderID: 9113,
                ProviderName: "dsf",
                PacTypeName: "PACOPT",
                TargetLOS: 3,
              },
            ],
            AnticipatedAcuteLos: 6,
          },
          {
            ToC_ID: "80810C9B-9CD6-4B84-35F1-08D9AB926CE8",
            CreatedDateTime: "2021-11-19 19:26:14.7560000",
            Version: 1,
            TransitionOfCareItems: [
              {
                ProviderID: 9106,
                ProviderName: "Apple Rehab - Tulsa",
                PacTypeName: "PACIPREHAB",
                TargetLOS: 10,
              },
            ],
            AnticipatedAcuteLos: 3,
          },
        ],
      },
      {
        PatientName: "CarlChipmunk",
        PatientDOB: "14-10-1947 00:00:00",
        PatientGender: "M",
        NavigatorFirstName: "DebbieM",
        NavigatorLastName: "1111-2002",
        ProcedureDescription: "AMI Test",
        ProcedureDate: null,
        IntakeID: 42760,
        TocCreatedDate: "2022-03-29 16:01:03.6520000",
        Status: "Approved",
        revision: [
          {
            ToC_ID: "E89D01D8-5548-4B93-0445-08DA119D539E",
            CreatedDateTime: "2022-04-11 19:25:11.3901320",
            Version: 4,
            TransitionOfCareItems: [
              {
                ProviderID: 9106,
                ProviderName: "Apple Rehab - Tulsa",
                PacTypeName: "IRF",
                TargetLOS: 1,
              },
            ],
            AnticipatedAcuteLos: 1,
          },
          {
            ToC_ID: "E6CF2570-1DA4-404F-4B47-08D9CBA92ADE",
            CreatedDateTime: "2022-04-12 01:25:48.0425534",
            Version: 1,
            TransitionOfCareItems: [
              {
                ProviderID: 9107,
                ProviderName: "Apple Rehab - Waco",
                PacTypeName: "PACIPREHAB",
                TargetLOS: 1,
              },
            ],
            AnticipatedAcuteLos: 1,
          },
        ],
      },
      {
        PatientName: "BarbieParka",
        PatientDOB: "04-03-1956 00:00:00",
        PatientGender: "M",
        NavigatorFirstName: "DebbieM",
        NavigatorLastName: "1111-2002",
        ProcedureDescription: "AMI Test",
        ProcedureDate: "2022-01-10 05:00:00.0000000",
        IntakeID: 42761,
        TocCreatedDate: "2022-01-05 21:28:09.2960000",
        Status: "Approved",
        revision: [
          {
            ToC_ID: "903EB577-C4D0-4A6C-F1B1-08D9D08F2EF7",
            CreatedDateTime: "2022-01-05 21:28:41.3270000",
            Version: 1,
            TransitionOfCareItems: [
              {
                ProviderID: 9107,
                ProviderName: "Apple Rehab - Waco",
                PacTypeName: "SNF",
                TargetLOS: 7,
              },
            ],
            AnticipatedAcuteLos: 2,
          },
        ],
      },
      {
        PatientName: "BarbieParka",
        PatientDOB: "04-03-1956 00:00:00",
        PatientGender: "M",
        NavigatorFirstName: "DebbieM",
        NavigatorLastName: "1111-2002",
        ProcedureDescription: "AMI Test",
        ProcedureDate: "2022-01-10 05:00:00.0000000",
        IntakeID: 42762,
        TocCreatedDate: "2022-01-05 23:01:09.1320000",
        Status: "Approved",
        revision: [
          {
            ToC_ID: "B1AA2CC0-D172-4FC1-F1B3-08D9D08F2EF7",
            CreatedDateTime: "2022-04-12 01:06:28.0732847",
            Version: 2,
            TransitionOfCareItems: [
              {
                ProviderID: 9106,
                ProviderName: "Apple Rehab - Tulsa",
                PacTypeName: "IRF",
                TargetLOS: 3,
              },
            ],
            AnticipatedAcuteLos: 1,
          },
          {
            ToC_ID: "0A2DC5B6-A8E7-4F31-F1B2-08D9D08F2EF7",
            CreatedDateTime: "2022-01-05 22:58:05.1520000",
            Version: 1,
            TransitionOfCareItems: [
              {
                ProviderID: 9106,
                ProviderName: "Apple Rehab - Tulsa",
                PacTypeName: "SNF",
                TargetLOS: 5,
              },
            ],
            AnticipatedAcuteLos: 1,
          },
        ],
      },
    ],
  },
};
